export const HISN_API_BASE = 'https://www.hisnmuslim.com/api';

export const HISN_TITLE_BN: Record<string, string> = {
  'supplications for when you wake up': 'ঘুম থেকে ওঠার সময়',
  'Invocation when getting dressed': 'কাপড় পরার সময়',
  'Invocation when putting on new clothes': 'নতুন কাপড় পরার সময়',
  'Invocation before entering the restroom': 'পায়খানায় প্রবেশের আগে',
  'Invocation for entering the restroom': 'পায়খানায় প্রবেশের আগে',
  'Invocation for leaving the restroom': 'পায়খানা থেকে বের হওয়ার পর',
  'What to say before performing ablution': 'ওজুর আগে',
  'What to say upon completing ablution': 'ওজুর পর',
  'What to say when leaving the home': 'বাড়ি থেকে বের হওয়ার সময়',
  'What to say when entering the home': 'বাড়িতে প্রবেশের সময়',
  'Invocation for going to the mosque': 'মসজিদে যাওয়ার সময়',
  'Invocation for entering the mosque': 'মসজিদে প্রবেশের সময়',
  'Invocation for leaving the mosque': 'মসজিদ থেকে বের হওয়ার সময়',
  'What to say upon hearing the Athan (call to prayer)': 'আজান সম্পর্কে',
  'Words of remembrance for morning and evening': 'সকাল ও সন্ধ্যার যিকির',
  'What to say before sleeping': 'ঘুমানোর আগে',
  'Invocation for riding in a vehicle or on an animal': 'যাত্রার সময়',
  'Invocation for travel': 'সফরের দোয়া',
  'What to say when entering the market': 'বাজারে প্রবেশে',
  'When sneezing': 'হাঁচি দিলে',
  'Upon breaking fast': 'ইফতারের সময়',
  'Before eating': 'খাওয়ার আগে',
  'Upon completing the meal': 'খাওয়ার পর',
  'For anxiety and sorrow': 'দুশ্চিন্তা ও দুঃখের সময়',
  'When visiting the sick': 'রোগী দেখতে গেলে',
  'For the deceased at the funeral prayer': 'জানাজার দোয়া',
  'Excellence of sending prayers upon the Prophet': 'দরুদ পাঠের ফজিলত',
};
